#服务端口号
server:
  port: 7001

#eureka 基本信息配置
eureka:
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false  # 关闭自我保护模式（缺省为打开）
    #剔除失效服务间隔
    eviction-interval-timer-in-ms: 2000
  instance:
    #注册到eureka的ip地址
    hostname: eureka7001
  client:
    serviceUrl:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: false
    #因为自己是为注册中心，不需要检索服务
    fetch-registry: false


spring:
  application:
    name: eureka
