#端口号
server:
  port: 7020

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka

spring:
  application:
    name: bus-server
  bus:
    trace:
      enabled: true
  rabbitmq:
    host: ${RABBIT_MQ_HOST:192.168.36.133}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

