server:
  port: 9001

spring:
  application:
    name: consumer-feign

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka

feign:
  hystrix:
    enabled: true   #开启断路器， 缺省值为false


