#端口号
server:
  port: 7010

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka
spring:
  application:
    #注册中心应用名称
    name: config-server
  rabbitmq:
    host: 192.168.36.133
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          #git环境地址
          uri: https://github.com/kongliuyi/config.git
          ##搜索目录
          search-paths: /
      ##读取分支
      label: master
    bus:
      trace:
        enabled: true



management:
  endpoints:
    web:
      exposure:
        include: bus-refresh